<a href="https://colab.research.google.com/github/Humayun167/Python/blob/main/G2_221_15_5411.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
# This is formatted as code
```

# **Importing Library**

In [ ]:
import numpy as np

# **Array Attributes**

In [ ]:
a = np.array([1,2,3]) #1D
a

array([1, 2, 3])

In [ ]:
b= np.array([[1,2,3],
             [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
c= np.array([[1,2,3],
             [4,5,6],
             [7,8.5,9]])
c

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [7. , 8.5, 9. ]])

In [ ]:
d= np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
              [[10,11,12],
             [13,14,15],
               [55,66,77]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [55, 66, 77]]])

D-type

In [ ]:
a.dtype, b.dtype,c.dtype,d.dtype


(dtype('int64'), dtype('int64'), dtype('float64'), dtype('int64'))

# **NDIM**

In [ ]:
a.ndim,b.ndim,c.ndim,d.ndim,

(1, 2, 2, 3)

# Shape **Attribute**

In [ ]:
a.shape,b.shape,c.shape,d.shape,

((3,), (2, 3), (3, 3), (2, 3, 3))

# **SIZE Attribute**

In [ ]:
a.size,b.size,c.size,d.size,

(3, 6, 9, 18)

# Item **size**

In [ ]:
a.itemsize,b.itemsize,c.itemsize,d.itemsize,

(8, 8, 8, 8)

# **nbytes**

In [ ]:
a.nbytes,b.nbytes

(24, 48)

# **Array Operation**

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b<5

NameError: name 'b' is not defined

In [ ]:
b<=5

array([[ True,  True,  True],
       [ True,  True, False]])

In [ ]:
b==5

array([[False, False, False],
       [False,  True, False]])

In [ ]:
b!=5

array([[ True,  True,  True],
       [ True, False,  True]])

In [ ]:
x= np.array([[1,2,3],
             [4,5,6]])

NameError: name 'np' is not defined

In [ ]:
x


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
y= np.array([[7,8,9],
             [10,11,12]])

In [ ]:
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
z= x*y
z

array([[ 7, 16, 27],
       [40, 55, 72]])

In [ ]:
z=x%y
z

array([[1, 2, 3],
       [4, 5, 6]])

# Numpy **method**

In [ ]:
grades = np.array([[87,95,70],[50,60,80],[70,58,60],[70,99,50]])
grades


array([[87, 95, 70],
       [50, 60, 80],
       [70, 58, 60],
       [70, 99, 50]])

In [ ]:
grades.max()


99

In [ ]:
grades.min()

50

In [ ]:
grades.mean()

70.75

In [ ]:
grades.std()

15.790952050673406

In [ ]:
grades.mean(axis=1)

array([84.        , 63.33333333, 62.66666667, 73.        ])

# **Shallow Copies**

In [ ]:
num1 = np.arange(1,6)
num1

array([1, 2, 3, 4, 5])

In [ ]:
num2 = num1.view()
num2

array([1, 2, 3, 4, 5])

In [ ]:
print(id(num1))
print(id(num2))

134311969531120
134311969445360


# **Deep Copies**

In [ ]:
num3 = num2.copy()
num3

array([1, 2, 3, 4, 5])

In [ ]:
num2[4]*=5
num2

array([  1,   2,   3,   4, 125])

In [ ]:
num3


array([1, 2, 3, 4, 5])

# **Universal Function**

In [ ]:
num = np.arange(1,6) *5
num

array([ 5, 10, 15, 20, 25])

In [ ]:
n=np.add(num,5)
n-15

array([10, 15, 20, 25, 30])

In [ ]:
g=np.multiply(num,5)
g


array([ 25,  50,  75, 100, 125])

In [ ]:
g=np.power(num,3)
g

array([  125,  1000,  3375,  8000, 15625])

In [ ]:
g=np.sqrt(num)
g

array([2.23606798, 3.16227766, 3.87298335, 4.47213595, 5.        ])

In [ ]:
g=np.exp(num)
g



array([1.48413159e+02, 2.20264658e+04, 3.26901737e+06, 4.85165195e+08,
       7.20048993e+10])

In [ ]:
g=np.log10(num)
g

array([0.69897   , 1.        , 1.17609126, 1.30103   , 1.39794001])

In [ ]:
g=np.log(num)
g

array([1.60943791, 2.30258509, 2.7080502 , 2.99573227, 3.21887582])

In [ ]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [ ]:
theta = np.linspace(0,90,7)
theta

array([ 0., 15., 30., 45., 60., 75., 90.])

# **indexing and slicing**

In [ ]:
num = np.arange(0,110,10)
num

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
num[::]

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
num[3:8]

array([30, 40, 50, 60, 70])

In [ ]:
num[::-1]

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10,   0])

In [ ]:
num[7:2:-1]

array([70, 60, 50, 40, 30])

In [ ]:
grades


array([[87, 95, 70],
       [50, 60, 80],
       [70, 58, 60],
       [70, 99, 50]])

In [ ]:
grades[2,1] #row

58

In [ ]:
grades[1:4] #row

array([[50, 60, 80],
       [70, 58, 60],
       [70, 99, 50]])

In [ ]:
grades[[1,3]]

array([[50, 60, 80],
       [70, 99, 50]])

In [ ]:
grades[:,1]


array([95, 60, 58, 99])

In [ ]:
grades[:,1:3]

array([[95, 70],
       [60, 80],
       [58, 60],
       [99, 50]])

In [ ]:
grades[:,[0,2]]

array([[87, 70],
       [50, 80],
       [70, 60],
       [70, 50]])

**Reshaping**

In [ ]:
b_reshape = np.reshape(b,(3,2))
b_reshape

array([[1, 2],
       [3, 4],
       [5, 6]])

**Transposing**


In [ ]:
b


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.shape

(2, 3)

In [ ]:
b_transpose = np.transpose(b)
b_transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

# **Exercise 1**

In [ ]:
#a
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

second_row = arr[1]
print(second_row)

In [ ]:
#b
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

first_and_third_rows = arr[[0, 2]]
print(first_and_third_rows)

In [ ]:
#c
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

middle_three_columns = arr[:, 1:4]
print(middle_three_columns)


[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [ ]:
#d
import numpy as np

arr = np.array([[1,  2,  3,  4,  5],
                [6,  7,  8,  9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

element_12 = arr[2, 1]
element_13 = arr[2, 2]

print("Element 12:", element_12)
print("Element 13:", element_13)


Element 12: 12
Element 13: 13


In [ ]:
#e
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

third_row_reverse = arr[2, ::-1]
print("Third row in reverse order:", third_row_reverse)


Third row in reverse order: [15 14 13 12 11]


In [ ]:
#f
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

fourth_row = arr[3]
max_value = np.max(fourth_row)
min_value = np.min(fourth_row)
sum_value = np.sum(fourth_row)
mean_value = np.mean(fourth_row)
std_value = np.std(fourth_row)
var_value = np.var(fourth_row)

print("Max:", max_value)
print("Min:", min_value)
print("Sum:", sum_value)
print("Mean:", mean_value)
print("Standard Deviation:", std_value)
print("Variance:", var_value)


Max: 20
Min: 16
Sum: 90
Mean: 18.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


In [ ]:
#a
import numpy as np

array = np.array([[1, 3, 2, 4],
                  [8, 6, 5, 7],
                  [11, 10, 12, 9]])

transpose_array = np.transpose(array)

print(transpose_array)


[[ 1  8 11]
 [ 3  6 10]
 [ 2  5 12]
 [ 4  7  9]]


In [ ]:
#b
import numpy as np

array = np.array([[1, 3, 2, 4],
                  [8, 6, 5, 7],
                  [11, 10, 12, 9]])


reshaped_array = np.reshape(array, (4, 3))

print(reshaped_array)


[[ 1  3  2]
 [ 4  8  6]
 [ 5  7 11]
 [10 12  9]]
